name: math_game
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.17.0
  flame_audio: ^2.1.2
  firebase_core: ^4.0.0
  cupertino_icons: ^1.0.8
  firebase_analytics: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/player.png
    - assets/enemy.png
    - assets/bullet.png
    - assets/bg.png
    - assets/shoot.wav
    - assets/hit.wav